[workspace]
members = ["mainpatch", "prepatch"]
default-members = ["mainpatch", "prepatch"]
resolver = "2"

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
panic = "abort"
